"""NYC LL84 annual benchmarking source slice."""

from civix.domains.building_energy_emissions.adapters.sources.us.nyc_ll84.adapter import (
    DEFAULT_PAGE_SIZE,
    LL84_BASE_URL,
    LL84_DATASET_ID,
    LL84_DEFAULT_ORDER,
    LL84_SOURCE_RECORD_ID_FIELDS,
    LL84_SOURCE_SCOPE,
    NYC_JURISDICTION,
    SOURCE_ID,
    NycLl84Adapter,
    NycLl84FetchConfig,
)
from civix.domains.building_energy_emissions.adapters.sources.us.nyc_ll84.caveats import (
    LL84_CAVEAT_SOURCE_FIELD,
    LL84_CAVEAT_TAXONOMY_ID,
    LL84_CAVEAT_TAXONOMY_VERSION,
    NycLl84Caveat,
    nyc_ll84_caveat_categories,
)
from civix.domains.building_energy_emissions.adapters.sources.us.nyc_ll84.mapper import (
    METHODOLOGY_LABEL,
    METRICS_MAPPER_ID,
    METRICS_MAPPER_VERSION,
    REPORT_MAPPER_ID,
    REPORT_MAPPER_VERSION,
    SUBJECT_MAPPER_ID,
    SUBJECT_MAPPER_VERSION,
    NycLl84MetricsMapper,
    NycLl84ReportMapper,
    NycLl84SubjectMapper,
)
from civix.domains.building_energy_emissions.adapters.sources.us.nyc_ll84.schema import (
    LL84_BOROUGH_TAXONOMY,
    LL84_DATA_QUALITY_TAXONOMY,
    LL84_METER_ALERT_TAXONOMIES,
    LL84_OUT_FIELDS,
    LL84_PROPERTY_TYPE_TAXONOMY,
    LL84_RAW_SCHEMA,
    LL84_SCHEMA_VERSION,
    LL84_TAXONOMIES,
    LL84_TAXONOMY_VERSION,
)

__all__ = [
    "DEFAULT_PAGE_SIZE",
    "LL84_BASE_URL",
    "LL84_BOROUGH_TAXONOMY",
    "LL84_CAVEAT_SOURCE_FIELD",
    "LL84_CAVEAT_TAXONOMY_ID",
    "LL84_CAVEAT_TAXONOMY_VERSION",
    "LL84_DATASET_ID",
    "LL84_DATA_QUALITY_TAXONOMY",
    "LL84_DEFAULT_ORDER",
    "LL84_METER_ALERT_TAXONOMIES",
    "LL84_OUT_FIELDS",
    "LL84_PROPERTY_TYPE_TAXONOMY",
    "LL84_RAW_SCHEMA",
    "LL84_SCHEMA_VERSION",
    "LL84_SOURCE_RECORD_ID_FIELDS",
    "LL84_SOURCE_SCOPE",
    "LL84_TAXONOMIES",
    "LL84_TAXONOMY_VERSION",
    "METHODOLOGY_LABEL",
    "METRICS_MAPPER_ID",
    "METRICS_MAPPER_VERSION",
    "NYC_JURISDICTION",
    "REPORT_MAPPER_ID",
    "REPORT_MAPPER_VERSION",
    "SOURCE_ID",
    "SUBJECT_MAPPER_ID",
    "SUBJECT_MAPPER_VERSION",
    "NycLl84Adapter",
    "NycLl84Caveat",
    "NycLl84FetchConfig",
    "NycLl84MetricsMapper",
    "NycLl84ReportMapper",
    "NycLl84SubjectMapper",
    "nyc_ll84_caveat_categories",
]
