"""NYC DOT Traffic Speeds source package."""

from .adapter import (
    DEFAULT_BASE_URL,
    DEFAULT_PAGE_SIZE,
    NYC_JURISDICTION,
    NYC_TRAFFIC_SPEEDS_DATASET_CONFIG,
    NYC_TRAFFIC_SPEEDS_DATASET_ID,
    NYC_TRAFFIC_SPEEDS_RELEASE_CAVEATS,
    NYC_TRAFFIC_SPEEDS_SOURCE_SCOPE,
    SOCRATA_ORDER,
    SOURCE_ID,
)
from .mapper import (
    MAPPER_ID,
    MAPPER_VERSION,
    NycTrafficSpeedsMapper,
)
from .schema import (
    NYC_TRAFFIC_SPEEDS_SCHEMA,
    NYC_TRAFFIC_SPEEDS_TAXONOMIES,
)

__all__ = [
    "DEFAULT_BASE_URL",
    "DEFAULT_PAGE_SIZE",
    "MAPPER_ID",
    "MAPPER_VERSION",
    "NYC_JURISDICTION",
    "NYC_TRAFFIC_SPEEDS_DATASET_CONFIG",
    "NYC_TRAFFIC_SPEEDS_DATASET_ID",
    "NYC_TRAFFIC_SPEEDS_RELEASE_CAVEATS",
    "NYC_TRAFFIC_SPEEDS_SCHEMA",
    "NYC_TRAFFIC_SPEEDS_SOURCE_SCOPE",
    "NYC_TRAFFIC_SPEEDS_TAXONOMIES",
    "NycTrafficSpeedsMapper",
    "SOCRATA_ORDER",
    "SOURCE_ID",
]
