"""NYC LL97 covered-building inventory source slice."""

from civix.domains.building_energy_emissions.adapters.sources.us.nyc_ll97.adapter import (
    LL97_DATASET_ID,
    LL97_DEFAULT_BASE_URL,
    LL97_DEFAULT_FILENAME,
    LL97_DEFAULT_FILING_YEAR,
    LL97_DEFAULT_URL,
    LL97_SHEET_NAME,
    LL97_SOURCE_RECORD_ID_FIELDS,
    LL97_SOURCE_SCOPE,
    NYC_JURISDICTION,
    SOURCE_ID,
    NycLl97Adapter,
    NycLl97FetchConfig,
)
from civix.domains.building_energy_emissions.adapters.sources.us.nyc_ll97.caveats import (
    LL97_CAVEAT_SOURCE_FIELD,
    LL97_CAVEAT_TAXONOMY_ID,
    LL97_CAVEAT_TAXONOMY_VERSION,
    NycLl97Caveat,
    nyc_ll97_caveat_categories,
)
from civix.domains.building_energy_emissions.adapters.sources.us.nyc_ll97.mapper import (
    CASE_MAPPER_ID,
    CASE_MAPPER_VERSION,
    SUBJECT_MAPPER_ID,
    SUBJECT_MAPPER_VERSION,
    NycLl97CaseMapper,
    NycLl97SubjectMapper,
)
from civix.domains.building_energy_emissions.adapters.sources.us.nyc_ll97.schema import (
    LL97_COVERED_TAXONOMY,
    LL97_HEADER_NORMALIZATION,
    LL97_PATHWAY_TAXONOMY,
    LL97_RAW_FIELDS,
    LL97_RAW_SCHEMA,
    LL97_SCHEMA_VERSION,
    LL97_TAXONOMIES,
    LL97_TAXONOMY_VERSION,
)

__all__ = [
    "CASE_MAPPER_ID",
    "CASE_MAPPER_VERSION",
    "LL97_CAVEAT_SOURCE_FIELD",
    "LL97_CAVEAT_TAXONOMY_ID",
    "LL97_CAVEAT_TAXONOMY_VERSION",
    "LL97_COVERED_TAXONOMY",
    "LL97_DATASET_ID",
    "LL97_DEFAULT_BASE_URL",
    "LL97_DEFAULT_FILENAME",
    "LL97_DEFAULT_FILING_YEAR",
    "LL97_DEFAULT_URL",
    "LL97_HEADER_NORMALIZATION",
    "LL97_PATHWAY_TAXONOMY",
    "LL97_RAW_FIELDS",
    "LL97_RAW_SCHEMA",
    "LL97_SCHEMA_VERSION",
    "LL97_SHEET_NAME",
    "LL97_SOURCE_RECORD_ID_FIELDS",
    "LL97_SOURCE_SCOPE",
    "LL97_TAXONOMIES",
    "LL97_TAXONOMY_VERSION",
    "NYC_JURISDICTION",
    "SOURCE_ID",
    "SUBJECT_MAPPER_ID",
    "SUBJECT_MAPPER_VERSION",
    "NycLl97Adapter",
    "NycLl97CaseMapper",
    "NycLl97Caveat",
    "NycLl97FetchConfig",
    "NycLl97SubjectMapper",
    "nyc_ll97_caveat_categories",
]
