"""FEMA National Risk Index source slice."""

from civix.domains.hazard_risk.adapters.sources.us.fema_nri.adapter import (
    DEFAULT_PAGE_SIZE,
    FEMA_NRI_SOURCE_SCOPE,
    FEMA_NRI_TRACTS_DATASET_ID,
    FEMA_NRI_TRACTS_LAYER_NAME,
    FEMA_NRI_TRACTS_ORDER,
    FEMA_NRI_TRACTS_QUERY_URL,
    FEMA_NRI_TRACTS_SERVICE_URL,
    FEMA_NRI_TRACTS_SOURCE_CRS,
    SOURCE_ID,
    US_JURISDICTION,
    FemaNriTractsAdapter,
    FemaNriTractsFetchConfig,
)
from civix.domains.hazard_risk.adapters.sources.us.fema_nri.caveats import (
    FEMA_NRI_CAVEAT_TAXONOMY_ID,
    FEMA_NRI_CAVEAT_TAXONOMY_VERSION,
    FEMA_NRI_METADATA_SOURCE_FIELD,
    FemaNriCaveat,
    fema_nri_caveat_categories,
)
from civix.domains.hazard_risk.adapters.sources.us.fema_nri.mapper import (
    AREA_MAPPER_ID,
    AREA_MAPPER_VERSION,
    METHODOLOGY_LABEL,
    METHODOLOGY_URL,
    SCORES_MAPPER_ID,
    SCORES_MAPPER_VERSION,
    FemaNriAreaMapper,
    FemaNriScoresMapper,
)
from civix.domains.hazard_risk.adapters.sources.us.fema_nri.schema import (
    FEMA_NRI_RATING_TAXONOMIES,
    FEMA_NRI_SCHEMA_VERSION,
    FEMA_NRI_TAXONOMY_VERSION,
    FEMA_NRI_TRACTS_OUT_FIELDS,
    FEMA_NRI_TRACTS_SCHEMA,
    FEMA_NRI_TRACTS_TAXONOMIES,
    FEMA_NRI_VERSION_TAXONOMY,
    NRI_HAZARD_PREFIXES,
    NRI_VERSION_METADATA,
    NriVersionMetadata,
)

__all__ = [
    "AREA_MAPPER_ID",
    "AREA_MAPPER_VERSION",
    "DEFAULT_PAGE_SIZE",
    "FEMA_NRI_CAVEAT_TAXONOMY_ID",
    "FEMA_NRI_CAVEAT_TAXONOMY_VERSION",
    "FEMA_NRI_METADATA_SOURCE_FIELD",
    "FEMA_NRI_RATING_TAXONOMIES",
    "FEMA_NRI_SCHEMA_VERSION",
    "FEMA_NRI_SOURCE_SCOPE",
    "FEMA_NRI_TAXONOMY_VERSION",
    "FEMA_NRI_TRACTS_DATASET_ID",
    "FEMA_NRI_TRACTS_LAYER_NAME",
    "FEMA_NRI_TRACTS_ORDER",
    "FEMA_NRI_TRACTS_OUT_FIELDS",
    "FEMA_NRI_TRACTS_QUERY_URL",
    "FEMA_NRI_TRACTS_SCHEMA",
    "FEMA_NRI_TRACTS_SERVICE_URL",
    "FEMA_NRI_TRACTS_SOURCE_CRS",
    "FEMA_NRI_TRACTS_TAXONOMIES",
    "FEMA_NRI_VERSION_TAXONOMY",
    "METHODOLOGY_LABEL",
    "METHODOLOGY_URL",
    "NRI_HAZARD_PREFIXES",
    "NRI_VERSION_METADATA",
    "SCORES_MAPPER_ID",
    "SCORES_MAPPER_VERSION",
    "SOURCE_ID",
    "US_JURISDICTION",
    "FemaNriAreaMapper",
    "FemaNriCaveat",
    "FemaNriScoresMapper",
    "FemaNriTractsAdapter",
    "FemaNriTractsFetchConfig",
    "NriVersionMetadata",
    "fema_nri_caveat_categories",
]
