"""Toronto permanent bicycle counter source package."""

from .adapter import (
    DEFAULT_BASE_URL,
    DEFAULT_PAGE_SIZE,
    SOURCE_ID,
    TORONTO_BICYCLE_COUNTER_15MIN_DATASET_CONFIG,
    TORONTO_BICYCLE_COUNTER_15MIN_RESOURCE_NAME,
    TORONTO_BICYCLE_COUNTER_LOCATIONS_DATASET_CONFIG,
    TORONTO_BICYCLE_COUNTER_LOCATIONS_RESOURCE_NAME,
    TORONTO_BICYCLE_COUNTERS_DATASET_ID,
    TORONTO_BICYCLE_COUNTERS_JURISDICTION,
    TORONTO_BICYCLE_COUNTERS_RELEASE_CAVEATS,
    TORONTO_BICYCLE_COUNTERS_SOURCE_SCOPE,
    TorontoBicycleCounter15MinAdapter,
    TorontoBicycleCounterLocationsAdapter,
)
from .mapper import (
    COUNT_MAPPER_ID,
    MAPPER_VERSION,
    SITE_MAPPER_ID,
    TorontoBicycleCounter15MinMapper,
    TorontoBicycleCounterSiteMapper,
)
from .schema import (
    TORONTO_BICYCLE_COUNTER_15MIN_SCHEMA,
    TORONTO_BICYCLE_COUNTER_15MIN_TAXONOMIES,
    TORONTO_BICYCLE_COUNTER_LOCATIONS_SCHEMA,
    TORONTO_BICYCLE_COUNTER_LOCATIONS_TAXONOMIES,
)

__all__ = [
    "COUNT_MAPPER_ID",
    "DEFAULT_BASE_URL",
    "DEFAULT_PAGE_SIZE",
    "MAPPER_VERSION",
    "SITE_MAPPER_ID",
    "SOURCE_ID",
    "TORONTO_BICYCLE_COUNTERS_DATASET_ID",
    "TORONTO_BICYCLE_COUNTERS_JURISDICTION",
    "TORONTO_BICYCLE_COUNTERS_RELEASE_CAVEATS",
    "TORONTO_BICYCLE_COUNTERS_SOURCE_SCOPE",
    "TORONTO_BICYCLE_COUNTER_15MIN_DATASET_CONFIG",
    "TORONTO_BICYCLE_COUNTER_15MIN_RESOURCE_NAME",
    "TORONTO_BICYCLE_COUNTER_15MIN_SCHEMA",
    "TORONTO_BICYCLE_COUNTER_15MIN_TAXONOMIES",
    "TORONTO_BICYCLE_COUNTER_LOCATIONS_DATASET_CONFIG",
    "TORONTO_BICYCLE_COUNTER_LOCATIONS_RESOURCE_NAME",
    "TORONTO_BICYCLE_COUNTER_LOCATIONS_SCHEMA",
    "TORONTO_BICYCLE_COUNTER_LOCATIONS_TAXONOMIES",
    "TorontoBicycleCounter15MinAdapter",
    "TorontoBicycleCounter15MinMapper",
    "TorontoBicycleCounterLocationsAdapter",
    "TorontoBicycleCounterSiteMapper",
]
