"""FEMA Hazard Mitigation Assistance source slice."""

from civix.domains.hazard_mitigation.adapters.sources.us.fema_hma.adapter import (
    FEMA_HMA_PROJECTS_DATASET_CONFIG,
    FEMA_HMA_PROJECTS_DATASET_ID,
    FEMA_HMA_PROJECTS_ORDER,
    FEMA_HMA_PROJECTS_VERSION,
    FEMA_HMA_SOURCE_SCOPE,
    FEMA_HMA_TRANSACTIONS_DATASET_CONFIG,
    FEMA_HMA_TRANSACTIONS_DATASET_ID,
    FEMA_HMA_TRANSACTIONS_ORDER,
    FEMA_HMA_TRANSACTIONS_VERSION,
    SOURCE_ID,
    US_JURISDICTION,
    FemaHmaProjectsAdapter,
    FemaHmaTransactionsAdapter,
)
from civix.domains.hazard_mitigation.adapters.sources.us.fema_hma.caveats import (
    OPENFEMA_HMA_CAVEAT_TAXONOMY_ID,
    OPENFEMA_HMA_TAXONOMY_VERSION,
    OPENFEMA_METADATA_DESCRIPTION_FIELD,
    OpenFemaHmaCaveat,
    observed_openfema_hma_metadata_caveats,
    openfema_hma_caveat_categories,
)
from civix.domains.hazard_mitigation.adapters.sources.us.fema_hma.mapper import (
    MAPPER_VERSION,
    PROJECT_MAPPER_ID,
    TRANSACTION_MAPPER_ID,
    FemaHmaProjectMapper,
    FemaHmaTransactionMapper,
)
from civix.domains.hazard_mitigation.adapters.sources.us.fema_hma.schema import (
    FEMA_HMA_FUND_CODE_TAXONOMY,
    FEMA_HMA_PROJECT_STATUS_TAXONOMY,
    FEMA_HMA_PROJECT_TYPE_TAXONOMY,
    FEMA_HMA_PROJECTS_SCHEMA,
    FEMA_HMA_PROJECTS_TAXONOMIES,
    FEMA_HMA_SCHEMA_VERSION,
    FEMA_HMA_TRANSACTIONS_SCHEMA,
    FEMA_HMA_TRANSACTIONS_TAXONOMIES,
)

__all__ = [
    "FEMA_HMA_FUND_CODE_TAXONOMY",
    "FEMA_HMA_PROJECTS_DATASET_CONFIG",
    "FEMA_HMA_PROJECTS_DATASET_ID",
    "FEMA_HMA_PROJECTS_ORDER",
    "FEMA_HMA_PROJECTS_SCHEMA",
    "FEMA_HMA_PROJECTS_TAXONOMIES",
    "FEMA_HMA_PROJECTS_VERSION",
    "FEMA_HMA_PROJECT_STATUS_TAXONOMY",
    "FEMA_HMA_PROJECT_TYPE_TAXONOMY",
    "FEMA_HMA_SCHEMA_VERSION",
    "FEMA_HMA_SOURCE_SCOPE",
    "FEMA_HMA_TRANSACTIONS_DATASET_CONFIG",
    "FEMA_HMA_TRANSACTIONS_DATASET_ID",
    "FEMA_HMA_TRANSACTIONS_ORDER",
    "FEMA_HMA_TRANSACTIONS_SCHEMA",
    "FEMA_HMA_TRANSACTIONS_TAXONOMIES",
    "FEMA_HMA_TRANSACTIONS_VERSION",
    "MAPPER_VERSION",
    "OPENFEMA_HMA_CAVEAT_TAXONOMY_ID",
    "OPENFEMA_HMA_TAXONOMY_VERSION",
    "OPENFEMA_METADATA_DESCRIPTION_FIELD",
    "PROJECT_MAPPER_ID",
    "SOURCE_ID",
    "TRANSACTION_MAPPER_ID",
    "US_JURISDICTION",
    "FemaHmaProjectMapper",
    "FemaHmaProjectsAdapter",
    "FemaHmaTransactionMapper",
    "FemaHmaTransactionsAdapter",
    "OpenFemaHmaCaveat",
    "observed_openfema_hma_metadata_caveats",
    "openfema_hma_caveat_categories",
]
